### ISSUE TITLE
On module_3, get error: exec /code/docker/entrypoints/entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by Daniel-Ri** [bobby-didcoding/drf_course#1]
**Describe the issue**
I followed your tutorial in [this Youtube video](https://www.youtube.com/watch?v=tujhGdn1EMI). In the 3rd module, after running docker-compose, one service (port=8000) is not running due to an error `exec /code/docker/entrypoints/entrypoint.sh: no such file or directory`. 

**To Reproduce**
1. On root folder, run `docker compose up -d --build`

**Expected behavior**
All services (port=5000 and port=8000) can run.

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/47727255/205492470-3260fb13-5ecc-46fa-81e5-06aa8a64e01d.png)
When you open the `Container` Tab, you will see that there is "Running (1/2)" on the `Status`.
<br />
  
![Screenshot (4)_edit](https://user-images.githubusercontent.com/47727255/205492476-94275114-0da7-4027-a3f1-e1c5ba2f5ac3.png)
1. The logs contain the error message : `exec /code/docker/entrypoints/entrypoint.sh: no such file or directory` .
2. One service (port=8000) is `Restarting` but it doesn't stop on `Restarting`.
<br />

![Screenshot (5)](https://user-images.githubusercontent.com/47727255/205492480-48b51604-dec4-4840-92e8-d2a666247cce.png)
When open the details of the service (port=8000), you will see the logs of this service.  
<br />

**Desktop**
Windows 11

**Comment by bobby-didcoding** [comment]
Hi there,

t looks like the chmod script worked so I’m leaning towards the file being present. Can you change the line endings on the dockerfiles and entry points to CRLF, please?

Thanks
Bobby

**Comment by Daniel-Ri** [comment]
Thanks for your reply! The original line endings of `docker-compose.yml`, `Dockerfile`, `Dockerfile_app` and `entrypoint.sh` are CLRF before I run the `docker-compose` command.

**Comment by bobby-didcoding** [comment]
I have seen this before but I can't remember what caused it.
The entrypoint file can be found as the dockerfile runs the chmod command on it without failing. The failure occurs when calling the ENTRYPONT command. It could be down to some janky bash set up on your machine.

Try changing the ENTRYPOINT line with the following:
CMD [ "python", "manage.py" , "runserver"]

**Comment by bobby-didcoding** [comment]
Note: If it works, you'll also need to run the following in the docker CLI:
python manage.py makemigrations
python manage.py migrate

**Comment by bobby-didcoding** [comment]
Gotta love Docker...

![paul-rudd-anchorman-the-legend-of-ron-burgundy](https://user-images.githubusercontent.com/80459294/205618719-cbb091bd-e937-402f-b480-5aff87292a71.gif)
